services:
  - type: web
    name: gym-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Gym_Project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gym-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: gym-db
    databaseName: gym_db
    user: gym_user
    plan: free 