services:
  - type: web
    name: gym-project
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn STMS.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gym-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: gym-db
    databaseName: gym_db
    user: gym_user
    plan: free 