services:
  - type: web
    name: gym-project
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate auth --noinput
      python manage.py migrate contenttypes --noinput
      python manage.py migrate sessions --noinput
      python manage.py migrate admin --noinput
      python manage.py migrate gymapp --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn --pythonpath . STMS.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 300 --keep-alive 5
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gym-db
          property: connectionString
      - key: DB_PASSWORD
        fromDatabase:
          name: gym-db
          property: password
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: STMS.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: GUNICORN_CMD_ARGS
        value: "--log-level=warning"

databases:
  - name: gym-db
    databaseName: gymapp_9owe
    user: gymapp_9owe_user
    plan: free